- file: src=~/Documents/mac-ansible/roles/marie_mac/files/dotfiles/{{ item }}
        path=~/.{{ item }}
        state=link
  with_items:
    - gitconfig
    - gitignore_global

- name: zsh - git repo for prezto fork
  git: repo=git@github.com:adamchainz/prezto.git
       dest=~/.zprezto

- name: zsh - link in prezto files
  file: state=link src=~/.zprezto/runcoms/{{ item }} path=~/.{{ item }}
  with_items:
    - zlogin
    - zlogout
    - zprofile
    - zshenv
    - zshrc
    - zpreztorc
