- name: basic dotfiles
  file:
    src: "~/Documents/mac-ansible/roles/marie_mac/files/dotfiles/{{ item }}"
    path: "~/.{{ item }}"
    state: link
  with_items:
    - gitconfig
    - gitignore_global

- name: sublime text 3 settings
  file:
    src: ~/Documents/mac-ansible/roles/marie_mac/files/sublime_text_3_settings
    path: ~/Library/Application Support/Sublime Text 3/Packages/User
    state: directory

- name: sketch plugins
  copy:
    src: ~/Documents/mac-ansible/roles/marie_mac/files/sketch_plugins/
    dest: ~/Library/Application Support/com.bohemiancoding.sketch3/Plugins/
    force: no

- name: zsh - git repo for prezto fork
  git:
    repo: git@github.com:emache/prezto.git
    dest: ~/.zprezto

- name: zsh - link in prezto files
  file:
    state: link
    src: "~/.zprezto/runcoms/{{ item }}"
    path: "~/.{{ item }}"
  with_items:
    - zlogin
    - zlogout
    - zprofile
    - zshenv
    - zshrc
    - zpreztorc
